//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovjeceNeLjutiSe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Jezik_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Jezik_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovjeceNeLjutiSe.Jezik-de-DE", typeof(Jezik_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLAU.
        /// </summary>
        internal static string pCheckBoxB {
            get {
                return ResourceManager.GetString("pCheckBoxB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRÜN.
        /// </summary>
        internal static string pCheckBoxG {
            get {
                return ResourceManager.GetString("pCheckBoxG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROT.
        /// </summary>
        internal static string pCheckBoxR {
            get {
                return ResourceManager.GetString("pCheckBoxR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GELB.
        /// </summary>
        internal static string pCheckBoxY {
            get {
                return ResourceManager.GetString("pCheckBoxY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPIEL BEGINNEN.
        /// </summary>
        internal static string pDugmeStart {
            get {
                return ResourceManager.GetString("pDugmeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MENSCH.
        /// </summary>
        internal static string pLabel1 {
            get {
                return ResourceManager.GetString("pLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÄRGERE.
        /// </summary>
        internal static string pLabel2 {
            get {
                return ResourceManager.GetString("pLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DICH.
        /// </summary>
        internal static string pLabel3 {
            get {
                return ResourceManager.GetString("pLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICHT.
        /// </summary>
        internal static string pLabel4 {
            get {
                return ResourceManager.GetString("pLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensch ärgere dich nicht.
        /// </summary>
        internal static string pNazivForme {
            get {
                return ResourceManager.GetString("pNazivForme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Namen der rote Spieler !!!.
        /// </summary>
        internal static string pPorukaCrveni {
            get {
                return ResourceManager.GetString("pPorukaCrveni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Namen der blaue Spieler !!!.
        /// </summary>
        internal static string pPorukaPlavi {
            get {
                return ResourceManager.GetString("pPorukaPlavi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die minimale Anzahl von Spielern ist 2 !!!.
        /// </summary>
        internal static string pPorukaStart {
            get {
                return ResourceManager.GetString("pPorukaStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Namen der grüne Spieler !!!.
        /// </summary>
        internal static string pPorukaZeleni {
            get {
                return ResourceManager.GetString("pPorukaZeleni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie den Namen der gelbe Spieler !!!.
        /// </summary>
        internal static string pPorukaZuti {
            get {
                return ResourceManager.GetString("pPorukaZuti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wechseln Sie, um an den nächsten Spieler.
        /// </summary>
        internal static string tTolTipB {
            get {
                return ResourceManager.GetString("tTolTipB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derzeit spielt rote Spieler.
        /// </summary>
        internal static string tTolTipL0 {
            get {
                return ResourceManager.GetString("tTolTipL0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derzeit spielt gelbe Spieler.
        /// </summary>
        internal static string tTolTipL1 {
            get {
                return ResourceManager.GetString("tTolTipL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derzeit spielt blaue Spieler.
        /// </summary>
        internal static string tTolTipL2 {
            get {
                return ResourceManager.GetString("tTolTipL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Derzeit spielt grüne Spieler.
        /// </summary>
        internal static string tTolTipL3 {
            get {
                return ResourceManager.GetString("tTolTipL3", resourceCulture);
            }
        }
    }
}
